---
adj_data:
  sensor_ids_file: 170  # 节点个数，或者节点编号文件
  distance_file: datasets/PEMS08/PEMS08.csv
  normalized_k: 0.1
  output_pkl_file: null  # null表示默认路径
  graph_type: direct

traffic_data:
  data_file: datasets/PEMS08/PEMS08.npz
  data_file_type: npz  # 数据集文件类型，后缀，["npz", "h5"]
  add_time_in_day: true
  add_day_in_week: true
  output_npz_file: null  # null表示默认路径
  split_list:  # 划分比例：训练集、验证集、测试集
    - 6
    - 2
    - 2